title: Subscription Framework
description: 
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
markdown: GFM
highlighter: rouge

# Set custom domain URL
url: "https://subscription-framework.cadtasticsolutions.com"

# Leave baseurl empty since you're using a root domain
baseurl: ""

# Repository metadata for GitHub Pages
repository: Cadtastic-Solutions/Subscription-Framework

# Pagination settings
paginate: 5
paginate_path: "/page:num"

# Author information
author: "Addam Boord"

# Exclude unnecessary files from the build
exclude:
  - README.md
  - .gitignore
